[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

[profile.default.invariant]
seed = 1
runs = 256 # default == 256
depth = 15 # default == 15
fail_on_revert = true

[rpc_endpoints]
mainnet = "${ALCHEMY_ETH_API_URL}"

# See more format options https://book.getfoundry.sh/reference/config/formatter
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
# If function parameters are multiline then always put the function attributes on separate lines
func_attrs_with_params_multiline = true
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
